version: '3'

networks:
    laravel:

services:
    composer:
        image: composer:latest
        container_name: composer    
        volumes: 
            - ./:/var/www/html/
        working_dir: /var/www/html
        networks:
            - laravel

    php:
        container_name: php
        build: 
            context: .
            dockerfile: Dockerfile    
        volumes:
            - ./:/var/www/html
        networks: 
            - laravel
        tty: true
        working_dir: /var/www/html/laravel
     
    mysql: 
        container_name: mysql       
        image: mysql:8
        tty: true
        environment: 
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - laravel
            
    redis:
        container_name: redis
        image: redis:5
        volumes:
            - redisdata:/data
        networks: 
            - laravel

    nginx:
        depends_on: 
            - php
            - mysql
        container_name: nginx
        image: nginx:1.17
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - laravel

volumes:
    mysqldata:
    redisdata:

